/*
 * Copyright (c) 2020. Temple3x (temple3x@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// xlogtest implements functions to generate temporary loggers.
package xlogtest

import (
	"io/ioutil"
	"os"
	"path/filepath"

	"github.com/zaibyte/pkg/config"
	"github.com/zaibyte/pkg/xlog"
)

var (
	logDir     = ""
	errLogName = "error.log"
	accLogName = "access.log"

	el *xlog.ErrorLogger
	al *xlog.AccessLogger
)

// New creates xlog.ErrorLogger & xlog.AccessLogger
// and init global logger.
//
// Log files will be placed in logDir which is in the $TMPDIR.
// The directory name is generated by taking pattern and applying a
// random string to the end.
func New(pattern string) (*xlog.ErrorLogger, *xlog.AccessLogger) {
	config.Adjust(&pattern, "xlog-test")
	var err error
	logDir, err = ioutil.TempDir(os.TempDir(), pattern)
	if err != nil {
		panic(err)
	}

	svrCfg := &xlog.ServerConfig{
		AccessLogOutput: filepath.Join(logDir, accLogName),
		ErrorLogOutput:  filepath.Join(logDir, errLogName),
		ErrorLogLevel:   "",
		Rotate:          xlog.RotateConfig{},
	}

	el, al, err = svrCfg.MakeAppLogger("", 1)
	if err != nil {
		panic(err)
	}
	return el, al
}

// Sync syncs loggers.
func Sync() {
	el.Sync()
	al.Sync()
}

// Clean cleans up loggers directory.
func Clean() {
	el.Close()
	al.Close()

	os.RemoveAll(logDir)
}
